=== hmrc/individuals-reliefs-api/resources/public/api/conf/3.0/schemas/relief_investments_retrieve/def2/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "TY 2025-26 onwards",
  "type": "object",
  "properties": {
    "submittedOn": {
      "description": "The date the investment relief was added. It must be provided in the format `YYYY-MM-DDThh:mm:ss.SSSZ`",
      "format": "date-time",
      "type": "string",
      "example": "2019-04-04T01:01:01.000Z"
    },
    "vctSubscription": {
      "description": "Financial details about VCT subscriptions income",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uniqueInvestmentRef": {
            "description": "The Unique Investment Reference (UIR) or the name of the authorising tax office as shown on the certificate.",
            "type": "string",
            "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
            "example": "12345678"
          },
          "name": {
            "description": "The name of the investment or fund.",
            "type": "string",
            "pattern": "^[0-9a-zA-Z{À-˿'}\\- _&`():.'^]{1,105}$",
            "example": "VCT fund"
          },
          "dateOfInvestment": {
            "description": "The date of the investment.\n\nDate in the format `YYYY-MM-DD`",
            "type": "string",
            "format": "date",
            "example": "2018-04-06"
          },
          "amountInvested": {
            "description": "The total amount invested.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2000.99,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          },
          "reliefClaimed": {
            "description": "The amount on which relief is claimed for the tax year.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2000.99,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          }
        },
        "required": [
          "dateOfInvestment",
          "name",
          "reliefClaimed"
        ],
        "additionalProperties": false
      }
    },
    "eisSubscription": {
      "description": "Financial details about EIS subscriptions income.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uniqueInvestmentRef": {
            "description": "The Unique Investment Reference (UIR) or the name of the authorising tax office as shown on the certificate.",
            "type": "string",
            "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
            "example": "12345678"
          },
          "name": {
            "description": "The name of the investment or fund",
            "type": "string",
            "pattern": "^[0-9a-zA-Z{À-˿'}\\- _&`():.'^]{1,105}$",
            "example": "EIS fund"
          },
          "knowledgeIntensive": {
            "description": "Companies that are carrying out research, development or innovation.",
            "type": "boolean",
            "example": true
          },
          "dateOfInvestment": {
            "description": "The date of the investment.\n\nDate in the format `YYYY-MM-DD`",
            "format": "date",
            "type": "string",
            "example": "2018-04-06"
          },
          "amountInvested": {
            "description": "The total amount invested.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2000.99,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          },
          "reliefClaimed": {
            "description": "The amount on which relief is claimed for the tax year.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2000.99,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          }
        },
        "required": [
          "dateOfInvestment",
          "knowledgeIntensive",
          "name",
          "uniqueInvestmentRef",
          "reliefClaimed"
        ],
        "additionalProperties": false
      }
    },
    "communityInvestment": {
      "description": "Financial details about community investment income.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uniqueInvestmentRef": {
            "description": "The Unique Investment Reference (UIR) or the name of the authorising tax office as shown on the certificate.",
            "type": "string",
            "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
            "example": "12345678"
          },
          "name": {
            "description": "The name of the investment or fund.",
            "type": "string",
            "pattern": "^[0-9a-zA-Z{À-˿'}\\- _&`():.'^]{1,105}$",
            "example": "CI X"
          },
          "dateOfInvestment": {
            "description": "The date of the investment.\n\nDate in the format `YYYY-MM-DD`",
            "format": "date",
            "type": "string",
            "example": "2018-04-06"
          },
          "amountInvested": {
            "description": "The total amount invested.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2000.99,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          },
          "reliefClaimed": {
            "description": "The amount of relief being claimed for the year.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2000.99,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          }
        },
        "required": [
          "uniqueInvestmentRef",
          "reliefClaimed"
        ],
        "additionalProperties": false
      }
    },
    "seedEnterpriseInvestment": {
      "description": "Financial details about Seed Investment Income.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uniqueInvestmentRef": {
            "description": "The Unique Investment Reference (UIR) or the name of the authorising tax office as shown on the certificate.",
            "type": "string",
            "pattern": "^[0-9a-zA-Z{À-˿’}\\- _&`():.'^]{1,90}$",
            "example": "12345678"
          },
          "companyName": {
            "description": "The name of the company holding the investment.",
            "type": "string",
            "pattern": "^[0-9a-zA-Z{À-˿'}\\- _&`():.'^]{1,105}$",
            "example": "Company Inc"
          },
          "dateOfInvestment": {
            "description": "The date of the investment.\n\nDate in the format `YYYY-MM-DD`",
            "format": "date",
            "type": "string",
            "example": "2018-04-06"
          },
          "amountInvested": {
            "description": "The total amount invested.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2000.99,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          },
          "reliefClaimed": {
            "description": "The amount on which relief is claimed for the tax year.\n\nThe value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2000.99,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          }
        },
        "required": [
          "dateOfInvestment",
          "companyName",
          "uniqueInvestmentRef",
          "reliefClaimed"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "submittedOn"
  ],
  "additionalProperties": false
}

=== hmrc/individuals-reliefs-api/resources/public/api/conf/3.0/examples/relief_investments_retrieve/def2/response.json
{
  "submittedOn": "2019-04-04T01:01:01.000Z",
  "vctSubscription":[
    {
      "uniqueInvestmentRef": "VCTREF",
      "name": "VCT Fund X",
      "dateOfInvestment": "2018-04-16",
      "amountInvested": 23312.00,
      "reliefClaimed": 1334.00
    }
  ],
  "eisSubscription":[
    {
      "uniqueInvestmentRef": "XTAL",
      "name": "EIS Fund X",
      "knowledgeIntensive": true,
      "dateOfInvestment": "2020-12-12",
      "amountInvested": 23312.00,
      "reliefClaimed": 43432.00
    }
  ],
  "communityInvestment": [
    {
      "uniqueInvestmentRef": "CIREF",
      "name": "CI X",
      "dateOfInvestment": "2020-12-12",
      "amountInvested": 6442.00,
      "reliefClaimed": 2344.00
    }
  ],
  "seedEnterpriseInvestment": [
    {
      "uniqueInvestmentRef": "1234121A",
      "companyName": "Company Inc",
      "dateOfInvestment": "2020-12-12",
      "amountInvested": 123123.22,
      "reliefClaimed": 3432.00
    }
  ]
}
