=== hmrc/individuals-reliefs-api/resources/public/api/conf/1.0/schemas/amend_relief_other_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Amend Other Reliefs",
  "description": "Allows the amendments of other reliefs",
  "type": "object",
  "properties": {
    "nonDeductableLoanInterest": {
      "description": "Details of non-deductable loan interest claimed",
      "type": "object",
      "properties": {
        "customerReference": {
          "description": "A reference or friendly name used by the customer.",
          "type": "string",
          "example": "INPOLY123A"
        },
        "reliefClaimed": {
          "description": "The amount of relief being claimed for the tax year. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        }
      },
      "required": [
        "reliefClaimed"
      ],
      "additionalProperties": false
    },
    "payrollGiving": {
      "description": "Details of payroll giving relief claimed.",
      "type": "object",
      "properties": {
        "customerReference": {
          "description": "A reference or friendly name used by the customer.",
          "type": "string",
          "example": "INPOLY123A"
        },
        "reliefClaimed": {
          "description": "The amount of relief being claimed for the tax year. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        }
      },
      "required": [
        "reliefClaimed"
      ],
      "additionalProperties": false
    },
    "qualifyingDistributionRedemptionOfSharesAndSecurities": {
      "description": "Details of qualifying shares and securities distributed that qualify for relief.",
      "type": "object",
      "properties": {
        "customerReference": {
          "description": "A reference or friendly name used by the customer.",
          "type": "string",
          "example": "INPOLY123A"
        },
        "amount": {
          "description": "The amount of relief claimed on redemption of bonus shares.",
          "type": "number",
          "example": "2000.99"
        }
      },
      "required": [
        "amount"
      ],
      "additionalProperties": false
    },
    "maintenancePayments": {
      "description": "Details of maintenance payments made to an ex-spouse.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "customerReference": {
            "description": "A reference or friendly name used by the customer.",
            "type": "string",
            "example": "INPOLY123A"
          },
          "exSpouseName": {
            "description": "The name of the ex-spouse who receives the payment.",
            "type": "string"
          },
          "exSpouseDateOfBirth": {
            "description": "The date the ex-spouse was born.",
            "type": "string",
            "example": "2018-04-06"
          },
          "amount": {
            "description": "The amount paid to a former spouse or civil partner who was born before 6 April 1935. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": "2000.99"
          }
        },
        "required": [
          "customerReference"
        ],
        "additionalProperties": false
      }
    },
    "postCessationTradeReliefAndCertainOtherLosses": {
      "description": "Details of trade reliefs and other losses post cessation of a business.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "customerReference": {
            "description": "A reference or friendly name used by the customer.",
            "type": "string",
            "example": "INPOLY123A"
          },
          "businessName": {
            "description": "The name of the business that has ceased trading.",
            "type": "string"
          },
          "dateBusinessCeased": {
            "description": "The date the business ceased trading. Date in the format: YYYY-MM-DD",
            "type": "string",
            "example": "2018-04-06"
          },
          "natureOfTrade": {
            "description": "The trading nature of the business.",
            "type": "string"
          },
          "incomeSource": {
            "description": "Income source identifier or UTR (Unique Taxpayer Reference).",
            "type": "string"
          },
          "amount": {
            "description": "The amount which can be deducted from chargeable gains. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": "2000.99"
          }
        },
        "required": [
          "customerReference"
        ],
        "additionalProperties": false
      }
    },
    "annualPaymentsMade": {
      "description": "Details of annual payments made.",
      "type": "object",
      "properties": {
        "customerReference": {
          "description": "A reference or friendly name used by the customer.",
          "type": "string",
          "example": "INPOLY123A"
        },
        "reliefClaimed": {
          "description": "The amount of relief being claimed for the tax year. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": "2000.99"
        }
      },
      "required": [
        "reliefClaimed"
      ],
      "additionalProperties": false
    },
    "qualifyingLoanInterestPayments": {
      "description": "Details of qualifying loan interest payments made.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "customerReference": {
            "description": "A reference or friendly name used by the customer.",
            "type": "string",
            "example": "INPOLY123A"
          },
          "lenderName": {
            "description": "The name of the individual, public group, private group, or financial institution that made the funds available.",
            "type": "string"
          },
          "reliefClaimed": {
            "description": "The amount of relief being claimed for the tax year. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": "2000.99"
          }
        },
        "required": [
          "customerReference",
          "reliefClaimed"
        ],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== hmrc/individuals-reliefs-api/resources/public/api/conf/1.0/examples/amend_relief_other_request.json
{
  "nonDeductableLoanInterest": {
    "customerReference": "myref",
    "reliefClaimed": 763.00
  },
  "payrollGiving": {
    "customerReference": "myref",
    "reliefClaimed": 154.00
  },
  "qualifyingDistributionRedemptionOfSharesAndSecurities": {
    "customerReference": "myref",
    "amount": 222.22
  },
  "maintenancePayments": [
    {
      "customerReference": "myref",
      "exSpouseName" : "Hilda",
      "exSpouseDateOfBirth": "2000-01-01",
      "amount": 222.22
    }
  ],
  "postCessationTradeReliefAndCertainOtherLosses": [
    {
      "customerReference": "myref",
      "businessName": "ACME Inc",
      "dateBusinessCeased": "2019-08-10",
      "natureOfTrade": "Widgets Manufacturer",
      "incomeSource": "AB12412/A12",
      "amount": 222.22
    }
  ],
  "annualPaymentsMade": {
    "customerReference": "myref",
    "reliefClaimed": 763.00
  },
  "qualifyingLoanInterestPayments": [
    {
      "customerReference": "myref",
      "lenderName": "Maurice",
      "reliefClaimed": 763.00
    }
  ]
}
