=== hmrc/individuals-reliefs-api/resources/public/api/conf/3.0/schemas/retrieve_relief_foreign_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Foreign Reliefs",
  "description": "Allows the retrieval of foreign reliefs",
  "type": "object",
  "properties": {
    "submittedOn": {
      "description": "The date the foreign reliefs were added. It must be provided in the format `YYYY-MM-DDThh:mm:ss.SSSZ`",
      "format": "date-time",
      "type": "string",
      "example": "2019-04-04T01:01:01.000Z"
    },
    "foreignTaxCreditRelief": {
      "description": "Relief on foreign tax paid to another country on overseas income.",
      "type": "object",
      "properties": {
        "amount": {
          "description": "The amount of Foreign Tax Credit Relief (FTCR). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 2000.99,
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99
        }
      },
      "required": [
        "amount"
      ],
      "additionalProperties": false
    },
    "foreignIncomeTaxCreditRelief": {
      "description": "Financial details about foreign income tax credit relief.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "countryCode": {
            "description": "A three-letter code that represents a country name. The value must be ISO 3166-1 alpha-3",
            "type": "string",
            "example": "FRA"
          },
          "foreignTaxPaid": {
            "description": "The amount of foreign Tax Paid on foreign income tax credit relief. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 4526.94,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          },
          "taxableAmount": {
            "description": "The amount of foreign Tax Paid on foreign income tax credit relief. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
            "type": "number",
            "example": 2963.95,
            "multipleOf": 0.01,
            "minimum": 0,
            "maximum": 99999999999.99
          },
          "employmentLumpSum": {
            "description": "A boolean indicating whether employment lump sum for foreign tax credit relief has been claimed.",
            "type": "boolean",
            "example": false
          }
        },
        "required": [
          "countryCode",
          "employmentLumpSum",
          "taxableAmount"
        ],
        "additionalProperties": false
      }
    },
    "foreignTaxForFtcrNotClaimed": {
      "description": "Object that holds the key value for foreign tax for FTCR not claimed",
      "type": "object",
      "properties": {
        "amount": {
          "description": "The amount paid on foreign tax not claimed (FTRC). The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "example": 2000.99,
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99
        }
      },
      "required": [
        "amount"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "submittedOn"
  ],
  "additionalProperties": false
}

=== hmrc/individuals-reliefs-api/resources/public/api/conf/3.0/examples/retrieve_reliefs_foreign_response.json
{
  "submittedOn": "2019-04-04T01:01:01.000Z",
  "foreignTaxCreditRelief": {
    "amount": 5000.99
  },
  "foreignIncomeTaxCreditRelief": [
    {
      "countryCode": "FRA",
      "foreignTaxPaid": 4567.69,
      "taxableAmount": 2853.13,
      "employmentLumpSum": false
    }
  ],
  "foreignTaxForFtcrNotClaimed": {
    "amount": 3456.97
  }
}
